### ISSUE TITLE
Uncaught TypeError: Cannot read property 'markerLayers' of undefined

### ISSUE THREAD

**Issue by jkutemeier** [benwbooth/atom-persistent-undo#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.0
**System**: Mac OS X 10.11.3
**Thrown From**: [persistent-undo](https://github.com/benwbooth/atom-persistent-undo) package, v1.1.0
### Stack Trace

Uncaught TypeError: Cannot read property 'markerLayers' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:1002

TypeError: Cannot read property 'markerLayers' of undefined
    at History.module.exports.History.serializeSnapshot (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/history.js:398:19)
    at History.module.exports.History.serializeStack (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/history.js:357:42)
    at History.module.exports.History.serialize (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/history.js:307:25)
    at /Users/kutemeie/.atom/packages/persistent-undo/lib/persistent-undo.coffee:22:55
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1082:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1074:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:16 core:select-all (atom-text-editor.editor.emacs-plus.is-focused)
     -0:15.4.0 core:backspace (atom-text-editor.editor.emacs-plus.is-focused)
     -0:15.1.0 core:paste (atom-text-editor.editor.emacs-plus.is-focused)
     -0:01.0 core:save (atom-text-editor.editor.emacs-plus.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "python-autopep8",
      "language-python"
    ],
    "followSymlinks": true,
    "ignoredNames": [
      ".git",
      "build",
      "dist",
      "*.egg*",
      ".gitignore",
      ".gitreview"
    ],
    "projectHome": "/Users/kutemeie/dev/sdp-repo",
    "themes": [
      "the-bespoke-pixel-ui",
      "the-bespoke-pixel-syntax"
    ]
  },
  "persistent-undo": {}
}
```
### Installed Packages

``` coffee
# User
MagicPython, v0.5.9
atom-beautify, v0.29.2
atom-python-debugger, v0.3.4
autocomplete-emojis, v2.3.0
autocomplete-python, v1.7.2
browser-plus, v0.0.60
clipboard-plus, v0.5.1
dockerletion, v0.2.0
emacs-plus, v0.11.0
filesize, v0.4.2
git-log, v0.4.1
hyperclick, v0.0.35
language-docker, v1.1.6
language-gherkin, v1.0.3
language-groovy, v0.6.0
language-hcl, v0.2.0
language-hocon, v1.1.0
language-log, v1.4.0
language-puppet, v0.19.1
language-splunk, v0.1.1
linter, v1.11.4
linter-docker, v0.1.2
linter-puppet-lint, v0.6.3
linter-pydocstyle, v0.4.2
linter-pylint, v1.2.0
linter-python-pep257, v0.0.1
linter-python-pep8, v0.2.0
linter-python-pyflakes, v0.1.0
minimap, v4.21.0
minimap-git-diff, v4.2.0
persistent-undo, v1.1.0
platformio-ide-terminal, v2.0.3
pretty-json, v1.0.3
project-manager, v2.9.7
python-indent, v0.4.3
python-isort, v0.0.7
python-yapf, v0.10.0
remote-edit, v1.8.24
the-bespoke-pixel-syntax, v1.0.3
the-bespoke-pixel-ui, v1.0.4
tree-view-git-status, v0.2.3

# Dev
No dev packages
```

**Comment by benwbooth** [comment]
Fixed, thanks!
