### ISSUE TITLE
Uncaught Error: incorrect header check

### ISSUE THREAD

**Issue by ginkel** [benwbooth/atom-persistent-undo#3]
[Enter steps to reproduce below:]

1. Open a folder
2. Observe the following error

**Atom Version**: 1.13.0
**Electron Version**: 1.4.14
**System**: linux 4.8.13-1-ARCH
**Thrown From**: [persistent-undo](https://github.com/benwbooth/atom-persistent-undo) package, v1.2.0

### Stack Trace

Uncaught Error: incorrect header check

```
At zlib.js:550

Error: incorrect header check
    at Zlib._handle.onerror (zlib.js:370:17)
    at Gunzip.Zlib._processChunk (zlib.js:540:30)
    at zlibBufferSync (zlib.js:239:17)
    at Object.exports.gunzipSync (zlib.js:175:10)
    at /home/tg/.atom/packages/persistent-undo/lib/persistent-undo.coffee:32:30
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "telemetryConsent": "no",
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
asciidoc-preview, v2.7.1 (active)
atom-pair, v2.0.10 (active)
autocomplete-paths, v1.0.5 (active)
double-click-tree-view, v1.1.0 (active)
persistent-undo, v1.2.0 (active)
vim-mode, v0.65.2 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (active)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (active)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.1 (inactive)
language-csharp, v0.13.0 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.47.1 (inactive)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```

**Comment by benwbooth** [comment]
Hm looks like the undo history zip file got corrupted. Not sure how or why that would happen...

**Comment by nicksergeant** [comment]
This error happens for me every time with the editor action `pane:split-right-and-copy-active-item`.

**Comment by brycefranzen** [comment]
Also having this issue. Just opened a project and the error was thrown.

**Comment by benwbooth** [comment]
Hey guys,

I'm not using Atom anymore. Can anyone provide a PR for this? Otherwise I may need to find a new maintainer.

**Comment by jrial** [comment]
For those wondering how to identify the offending file: on Unix you go to the persistent undo folder of the project you opened when the error appeared, and in there you zcat all files recursively. Pipe the standard output to /dev/null, so that only standard error gets printed to the console. In my case, it looked as follows:

```
nighty@saltmine ~$ cd ~/.atom/persistent-undo/home/nighty/workspaces/work/usd_api/
nighty@saltmine usd_api$ find . -type f -exec zcat {} > /dev/null \;

gzip: ./maileater/models.py: decompression OK, trailing garbage ignored
```

Restarting Atom after removing this file confirmed the issue was now resolved. This allows you to remove the history for the offending file only, without nuking the persistent history for the entire project.
