### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, mkdir '$ATOM_HOME/persistent-undo\D:'

### ISSUE THREAD

**Issue by Pustiu** [benwbooth/atom-persistent-undo#4]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0-beta2 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [persistent-undo](https://github.com/benwbooth/atom-persistent-undo) package 1.2.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, mkdir 'C:\Users\florin.sirbu\.atom\persistent-undo\D:'

```
At C:\Users\florin.sirbu\AppData\Local\atom\app-1.15.0-beta2\resources\app.asar\src\pane.js:1045

Error: ENOENT: no such file or directory, mkdir 'C:\Users\florin.sirbu\.atom\persistent-undo\D:'
    at Error (native)
    at fs.mkdirSync (fs.js:922:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:665:16)
    at Object.mkdirParent (/packages/persistent-undo/lib/persistent-undo.coffee:42:8)
    at Object.mkdirParent (/packages/persistent-undo/lib/persistent-undo.coffee:41:8)
    at Object.mkdirParent (/packages/persistent-undo/lib/persistent-undo.coffee:41:8)
    at Object.mkdirParent (/packages/persistent-undo/lib/persistent-undo.coffee:41:8)
    at Object.mkdirParent (/packages/persistent-undo/lib/persistent-undo.coffee:41:8)
    at Object.mkdirParent (/packages/persistent-undo/lib/persistent-undo.coffee:41:8)
    at /packages/persistent-undo/lib/persistent-undo.coffee:21:14
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1059:20)
    at TextBuffer.module.exports.TextBuffer.save (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1048:19)
    at TextEditor.module.exports.TextEditor.save (/app.asar/src/text-editor.js:910:26)
    at Pane.module.exports.Pane.saveItem (/app.asar/src/pane.js:753:18)
    at Pane.saveItem (/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (/app.asar/src/pane.js:736:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/app.asar/src/workspace.js:693:35)
    at /app.asar/src/register-default-commands.js:225:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:18.2.0 editor:outdent-selected-rows (input.hidden-input)
     -0:18 snippets:previous-tab-stop (input.hidden-input)
     -0:18 editor:outdent-selected-rows (input.hidden-input)
     -0:17.8.0 snippets:previous-tab-stop (input.hidden-input)
     -0:17.8.0 editor:outdent-selected-rows (input.hidden-input)
     -0:17.6.0 snippets:previous-tab-stop (input.hidden-input)
     -0:17.6.0 editor:outdent-selected-rows (input.hidden-input)
     -0:17.5.0 snippets:previous-tab-stop (input.hidden-input)
     -0:17.5.0 editor:outdent-selected-rows (input.hidden-input)
     -0:17.3.0 snippets:previous-tab-stop (input.hidden-input)
     -0:17.3.0 editor:outdent-selected-rows (input.hidden-input)
     -0:17.1.0 snippets:previous-tab-stop (input.hidden-input)
     -0:17.1.0 editor:outdent-selected-rows (input.hidden-input)
     -0:16.9.0 snippets:previous-tab-stop (input.hidden-input)
     -0:16.9.0 editor:outdent-selected-rows (input.hidden-input)
     -0:14.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-wordpress-hooks 0.2.2 
emmet 2.4.3 
git-plus 7.3.0 
persistent-undo 1.2.0 
Remote-FTP 0.10.5 
sass-autocompile 0.13.3 
seti-ui 1.6.1 
```

**Comment by benwbooth** [comment]
This is a windows-specific issue. I need to modify the history directory encoding to be able to handle drive letters with a colon
