### ISSUE TITLE
NodeError prevents Atom from saving

### ISSUE THREAD

**Issue by casalaina** [benwbooth/atom-persistent-undo#9]
I find this plugin very helpful, but after the update to Atom 1.39.1 x64, it's throwing the following error which prevents Atom from saving files:

```
Uncaught (in promise) NodeError: Callback must be a function
    at maybeCallback (fs.js:157:9)
    at Object.fs.writeFile (fs.js:1290:14)
    at /Users/michael/.atom/packages/persistent-undo/lib/persistent-undo.coffee:24:14
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1207528)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1209153
    at Array.map (<anonymous>)
    at Emitter.emitAsync (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1209116)
    at TextBuffer.saveTo (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:496403)
```

**Comment by benwbooth** [comment]
I published the new version, let me know if it's still not working. Thanks!

**Comment by casalaina** [comment]
Yep, back to normal. Thanks @benwbooth!
